class Studentdetails
{
public static void main(String []args)
{
	
Details.printing();
Details.names(0,"Radhika");
Details.names(1,"Nisarga");
Details.names(2,"Shweta");
Details.names(3,"Pooja");
Details.names(4,"Rani");
Details.names(5,"Soumya");
Details.names(6,"Deepa");
Details.names(7,"Anita");
Details.names(8,"Manjula");
Details.names(9,"Muskan");
Details.names(10,"Rajeshwari");
Details.names(11,"Akshat");
Details.names(12,"Bharat");
Details.names(13,"Sheetal");
Details.names(14,"Naveen");
Details.names(15,"Akshay");
Details.names(16,"Ullas");
Details.names(17,"Hemanth");
Details.names(18,"Lakkappa");
Details.names(19,"Umesh");
Details.names(20,"Arun");
Details.names(21,"Shankar");
Details.names(22,"Santosh");
Details.names(23,"Prashanth");
Details.names(24,"Mohan");
Details.names(25,"Sheetal");
Details.names(26,"Harshit");
Details.names(27,"Vila");
Details.printing();
Details.level(4,"Amruta");
Details.printing();
}
}